### ISSUE TITLE
Sometimes it never stops [Processing] even though it's done.

### ISSUE THREAD

**Issue by chrisfromredfin** [mdlutz24/drupal-meeting-parser#18] opened 2022-12-16 21:58 UTC
Looking at the code, near line 120 of scrape.js, I console.log'd the sidebar.scrollTop and sidebar.offsetHeight, and sidebar.scrollHeight and I see the following values:

<img width="201" alt="image" src="https://user-images.githubusercontent.com/278442/208195424-c7594183-7040-4c03-bda9-37d8317d786b.png">

scrape.js:120: 1402.5 705 2108

Unfortunately 1402.5 + 705 = 2107.5 and so is not >= 2108. 

What's the right thing here?

Original:
`let finished = (sidebar.scrollTop + sidebar.offsetHeight) >= sidebar.scrollHeight;`

`let finished = (Math.ceil(sidebar.scrollTop) + Math.ceil(sidebar.offsetHeight)) >= sidebar.scrollHeight;`
-or-
`let finished = Math.ceil(sidebar.scrollTop + sidebar.offsetHeight) >= sidebar.scrollHeight;`
-or-
`let finished = Math.ceil(sidebar.scrollTop + sidebar.offsetHeight) >= sidebar.scrollHeight - 1;`

??

**Comment by jurgenhaas** [comment] 2022-12-17 09:43
I'm seeing that as well, sometimes. It seems to be more likely to happen on longer threads. And when it does, the trailing `</table>` is missing. No big deal to add this manually. If it helps I could probably provide a link to a thread where this happens and can be reproduced.

**Comment by chrisfromredfin** [comment] 2022-12-20 20:11
FWIW I've been rolling with     
```js
let finished = Math.ceil(sidebar.scrollTop + sidebar.offsetHeight) >= sidebar.scrollHeight;
```
 
And it's been flawless for me. I'll open a PR.

**Comment by seantwalsh** [comment] 2023-02-09 17:43
@chrisfromredfin thanks for this working for me as well.

**Comment by mdlutz24** [comment] 2024-06-06 13:48
Merged, thanks!

**Closed as completed** 2024-06-06 13:48 UTC
